// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtBQredrfChPq3F28tTRqo4GRafCQgKQ',
    appId: '1:916093930011:web:0d611a9d3948d3092c06be',
    messagingSenderId: '916093930011',
    projectId: 'ecommerceapp-fa088',
    authDomain: 'ecommerceapp-fa088.firebaseapp.com',
    storageBucket: 'ecommerceapp-fa088.appspot.com',
    measurementId: 'G-74SEEDRW3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBud94jUI-kslDKj461ab4BMO-N_KV8_s0',
    appId: '1:916093930011:android:4d0986ff14b4ab612c06be',
    messagingSenderId: '916093930011',
    projectId: 'ecommerceapp-fa088',
    storageBucket: 'ecommerceapp-fa088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKe5dwXEeLlLKO8CU88D-90P3aLZ007k',
    appId: '1:916093930011:ios:e6ee135581961dfd2c06be',
    messagingSenderId: '916093930011',
    projectId: 'ecommerceapp-fa088',
    storageBucket: 'ecommerceapp-fa088.appspot.com',
    iosClientId: '916093930011-6kh6dsc0n6mt9j0rdmjsijg917kqqmg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}